# ═════════════════════════════════════════════════════════════════════════════
# Clean and Help targets
# ═════════════════════════════════════════════════════════════════════════════

clean:
	@echo "=== Cleaning build artifacts ==="
	-rm -rf "$(CURDIR)/build" "$(CURDIR)/sources-build" "$(CURDIR)/sources-patched" "$(CURDIR)/build-logs"
	@echo "=== Cleaning rootfs ==="
	-rm -rf "$(CURDIR)/rootfs"

distclean: clean
	@echo "=== Removing rootfs ==="
	-rm -rf "$(CURDIR)/rootfs"

# ═════════════════════════════════════════════════════════════════════════════
# Help
# ═════════════════════════════════════════════════════════════════════════════

help:
	@echo "Super Minimal Linux Libre — Cross-Compilation Build System"
	@echo ""
	@echo "Host:     $(HOST_TRIPLET)"
	@echo "Targets:  $(TARGETS)"
	@echo ""
	@echo "═══ Quick start ═══"
	@echo "  make build                build all packages + kernel for both targets"
	@echo "  make install              install both targets to rootfs/<arch>/"
	@echo ""
	@echo "═══ Build ═══"
	@echo "  make build                all userland + kernel (x86_64 + arm64)"
	@echo "  make userland             all userland (x86_64 + arm64)"
	@echo "  make <pkg>                one package for both targets"
	@echo "  make build-<pkg>          one package for both targets"
	@echo "  make ARCH=x86_64 build-<pkg>  one package for x86_64 only"
	@echo "  make ARCH=arm64 build-<pkg>   one package for arm64 only"
	@echo "  make kernel               both kernels (x86_64 + arm64)"
	@echo "  make ARCH=x86_64 kernel   x86_64 kernel only"
	@echo "  make ARCH=arm64 kernel    arm64 kernel only"
	@echo ""
	@echo "═══ Install ═══"
	@echo "  make install              install both targets"
	@echo "  make ARCH=x86_64 install  install x86_64 only"
	@echo "  make ARCH=arm64 install   install arm64 only"
	@echo "  make install-<pkg>        install one package for both targets"
	@echo "  make install-kernel       install both kernels"
	@echo "  make ARCH=x86_64 install-kernel  install x86_64 kernel"
	@echo "  make ARCH=arm64 install-kernel   install arm64 kernel"
	@echo ""
	@echo "═══ Disk Image ═══"
	@echo "  make disk-image           create bootable disk images (needs sudo)"
	@echo "  make ARCH=x86_64 disk-image   x86_64 disk image only"
	@echo "  make ARCH=arm64 disk-image    arm64 disk image only"
	@echo "  make qemu                 boot with QEMU (needs qemu-system-*)"
	@echo ""
	@echo "═══ Test ═══"
	@echo "  make test-dhcpcd          test DHCP on both arches"
	@echo "  make test-shutdown        test graceful shutdown on both arches"
	@echo "  make test                 all tests"
	@echo ""
	@echo "═══ Packages ═══"
	@echo "  $(USERLAND_PKGS)"
	@echo ""
	@echo "═══ Config ═══"
	@echo "  Host: $(HOST_TRIPLET)  |  Auto-detected config:"
	@echo "    x86_64:  prefix='$(CROSS_x86_64)'  sysroot=$(or $(SYSROOT_x86_64),<host native>)"
	@echo "    arm64:   prefix='$(CROSS_arm64)'   sysroot=$(or $(SYSROOT_arm64),<host native>)"
	@echo ""
	@echo "═══ Other ═══"
	@echo "  make check-env             validate toolchain and submodules"
	@echo "  make prepare-sources       copy and patch all sources"
	@echo "  make prepare-sources-<pkg> copy and patch one package"
	@echo "  make clean                 remove build artifacts"
	@echo "  make distclean             clean + remove rootfs"
	@echo "  make LOG=1 <target>        tee output to build-logs/<target>.log"
	@echo "  make STRIP=0 install       skip binary stripping"
	@echo ""
	@echo "═══ Directories ═══"
	@echo "  sources/           git submodules (never modified)"
	@echo "  sources-patched/   patched source trees (copy + patches, once per pkg)"
	@echo "  sources-build/     per-arch build output directories"
	@echo "  sources-patches/   per-package patch files"
	@echo "  build/             shared build infrastructure (fake-bin)"
	@echo "  rootfs/<arch>/     per-arch staging root filesystem"
	@echo "  build-logs/        per-target build logs"
