# ═════════════════════════════════════════════════════════════════════════════
# Clean and Help targets
# ═════════════════════════════════════════════════════════════════════════════

clean:
	@echo "=== Cleaning build artifacts ==="
	-rm -rf "$(CURDIR)/build" "$(CURDIR)/sources-build" "$(CURDIR)/sources-patched" "$(CURDIR)/build-logs"
	@echo "=== Cleaning rootfs ==="
	-rm -rf "$(CURDIR)/rootfs"
	@echo "=== Cleaning toolchain ==="
	-rm -rf "$(CURDIR)/toolchain"

distclean: clean
	@echo "=== Removing rootfs + toolchain ==="
	-rm -rf "$(CURDIR)/rootfs" "$(CURDIR)/toolchain"

# ═════════════════════════════════════════════════════════════════════════════
# Help
# ═════════════════════════════════════════════════════════════════════════════

help:
	@echo "Super Minimal Linux Libre — Cross-Compilation Build System"
	@echo ""
	@echo "Host:     $(HOST_TRIPLET)"
	@echo "Targets:  $(TARGETS)"

	@echo ""
	@echo "  make                     build all userland for ALL targets"
	@echo "  make all                 build all userland for ALL targets"
	@echo "  make userland            build all userland for ALL targets"
	@echo "  make userland-x86_64     build all userland for x86_64"
	@echo "  make userland-arm64      build all userland for arm64"
	@echo ""
	@echo "  make <pkg>              build <pkg> for ALL targets"
	@echo "  make build-<pkg>-x86_64 build <pkg> for x86_64 only"
	@echo "  make build-<pkg>-arm64  build <pkg> for arm64 only"
	@echo "  make install-<pkg>      install <pkg> for ALL targets"
	@echo ""
	@echo "  make install            install both targets to rootfs/<arch>/"
	@echo "  make install-x86_64     install x86_64 to rootfs/x86_64"
	@echo "  make install-arm64      install arm64 to rootfs/arm64"
	@echo ""
	@echo "  Toolchain (cross-compiler from source):"
	@echo "    make toolchain              build both x86_64 + arm64 toolchains"
	@echo "    make toolchain-x86_64       6-step cross-compiler for x86_64"
	@echo "    make toolchain-arm64        6-step cross-compiler for arm64"
	@echo "    make build-binutils-x86_64  step 1: binutils"
	@echo "    make linux-headers-x86_64   step 2: kernel headers"
	@echo "    make build-glibc-headers-x86_64  step 3: glibc headers"
	@echo "    make build-gcc-stage1-x86_64 step 4: GCC C only"
	@echo "    make build-glibc-x86_64      step 5: glibc full"
	@echo "    make build-gcc-final-x86_64  step 6: final GCC C/C++"
	@echo "    Installed to: $(TOOLCHAIN_PREFIX)/<arch>/"
	@echo ""
	@echo "  Kernel:"
	@echo "    make kernel              build both x86_64 + arm64 kernels"
	@echo "    make kernel-x86_64       build x86_64 kernel (kernel-x86_64.config)"
	@echo "    make kernel-arm64        build arm64 kernel (kernel-arm64.config)"
	@echo "    make install-kernel      install both kernels to rootfs/<arch>/boot/"
	@echo ""
	@echo "  Source preparation:"
	@echo "    make prepare-sources              copy & patch all sources"
	@echo "    make prepare-sources-<pkg>        copy & patch one package"
	@echo "    (sources/ never modified; patched copies go to sources-patched/)"
	@echo ""
	@echo "  Directories:"
	@echo "    sources/           git submodules (never modified)"
	@echo "    sources-patched/   patched source trees (copy + patches, once per pkg)"
	@echo "    sources-build/     per-arch build output directories"
	@echo "    sources-patches/   per-package patch files"
	@echo "    build/<arch>/      per-arch out-of-tree build artifacts"
	@echo "    rootfs/<arch>/     per-arch staging root filesystem"
	@echo "    toolchain/<arch>/  cross-compiler install (binutils + gcc + glibc + sysroot)"
	@echo ""
	@echo "  Packages:"
	@echo "    gnulib bootstrap:  coreutils, grep, sed, findutils,"
	@echo "                       diffutils, gzip, tar"
	@echo "    git+autoreconf:    procps-ng, util-linux"
	@echo "    git (configure):   bash, gawk, vim, iproute2, dhcpcd"
	@echo "    custom:            runit"
	@echo ""
	@echo "  Toolchain sources (git submodules):"
	@echo "    binutils, gcc, glibc, linux-libre (for kernel headers)"
