#!/bin/sh
# Write VM_DIR/vm.sh: a per-VM management script that runs vm/utm.sh (macOS)
# or vm/qemu.sh (elsewhere) with VM_DIR set to its own directory and the
# settings the VM was created with. Called by vm/utm.sh and vm/qemu.sh.
#
# Paths inside the repo are stored relative to it, so the same vm.sh works
# where the repo is mounted at a different path (e.g. inside a build VM).
#
# Usage: write-vm-sh.sh   (reads VM_DIR, KERNEL, INITRD, DISK, APPEND, MEM,
#                          CPUS, NET, ARCH from the environment)

set -eu

HERE=$(cd "$(dirname "$0")" && pwd)
REPO=$(cd "$HERE/.." && pwd)
VM_DIR=$(cd "$VM_DIR" && pwd)

# Shell-quote a value for the generated script
q() { printf "'%s'" "$(printf %s "$1" | sed "s/'/'\\\\''/g")"; }

# Expression for a path: relative to the repo when inside it
path_expr() {
	case $1 in
	"$REPO"/*) printf '"$REPO"/%s' "$(q "${1#"$REPO"/}")" ;;
	*) q "$1" ;;
	esac
}

# How vm.sh finds the repo: ../.. style when VM_DIR is inside it
case $VM_DIR in
"$REPO"/*)
	up=$(printf %s "${VM_DIR#"$REPO"/}" | sed 's|[^/][^/]*|..|g')
	repo_expr="\$(cd \"\$HERE/$up\" && pwd)"
	;;
*) repo_expr=$(q "$REPO") ;;
esac

settings=
# "[ -n "${VAR:-}" ] || VAR=<value>": caller's environment wins. (Quotes inside
# "${VAR:=...}" would be kept literally.)
add() { settings="$settings[ -n \"\${$1:-}\" ] || $1=$2
"; }
[ -z "${ARCH:-}" ] || add ARCH "$(q "$ARCH")"
[ -z "${KERNEL:-}" ] || add KERNEL "$(path_expr "$KERNEL")"
[ -z "${INITRD:-}" ] || add INITRD "$(path_expr "$INITRD")"
[ -z "${DISK:-}" ] || add DISK "$(path_expr "$DISK")"
[ -z "${APPEND:-}" ] || add APPEND "$(q "$APPEND")"
[ -z "${MEM:-}" ] || add MEM "$(q "$MEM")"
[ -z "${CPUS:-}" ] || add CPUS "$(q "$CPUS")"

tmp=$VM_DIR/.vm.sh.$$
cat >"$tmp" <<EOF
#!/bin/sh
# vm.sh — manage the VM in this directory. Generated by vm/write-vm-sh.sh
# (vm/utm.sh / vm/qemu.sh create); recreated on every create, do not edit.
#
# Runs vm/utm.sh on macOS and vm/qemu.sh elsewhere (RUNNER=utm|qemu picks
# one), with VM_DIR set to this directory and the settings below as defaults.
#   ./vm.sh help | version | start | console | exec CMD... | stop | status
#   ./vm.sh recreate | delete | list

set -eu
HERE=\$(cd "\$(dirname "\$0")" && pwd)
REPO=$repo_expr
export VM_DIR="\$HERE"
$settings
export ARCH KERNEL INITRD DISK APPEND MEM CPUS 2>/dev/null || true
if [ -z "\${RUNNER:-}" ]; then
	if [ "\$(uname -s)" = Darwin ]; then RUNNER=utm; else RUNNER=qemu; fi
fi
case \${1:-help} in
help | -h | --help)
	sed -n '2,8p' "\$0" | sed 's/^# \\{0,1\\}//'
	echo
	exec "\$REPO/vm/\$RUNNER.sh" help ;;
*) exec "\$REPO/vm/\$RUNNER.sh" "\$@" ;;
esac
EOF
chmod 755 "$tmp"
mv "$tmp" "$VM_DIR/vm.sh"
